/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LatestRouteImport } from './routes/latest'
import { Route as NewsroomRouteImport } from './routes/newsroom'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAuthorsRouteImport } from './routes/admin.authors'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCommentsRouteImport } from './routes/admin.comments'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminOversightRouteImport } from './routes/admin.oversight'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminSubmissionsRouteImport } from './routes/admin.submissions'
import { Route as AdminTagsRouteImport } from './routes/admin.tags'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthAdminRouteImport } from './routes/auth.admin'
import { Route as AuthJournalistRouteImport } from './routes/auth.journalist'
import { Route as AuthStaffRouteImport } from './routes/auth.staff'
import { Route as AuthorSlugRouteImport } from './routes/author.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as NewsroomIndexRouteImport } from './routes/newsroom.index'
import { Route as NewsroomProfileRouteImport } from './routes/newsroom.profile'
import { Route as TagSlugRouteImport } from './routes/tag.$slug'
import { Route as AdminPostsIndexRouteImport } from './routes/admin.posts.index'
import { Route as AdminPostsIdRouteImport } from './routes/admin.posts.$id'
import { Route as AdminReviewIdRouteImport } from './routes/admin.review.$id'
import { Route as NewsroomWriteIdRouteImport } from './routes/newsroom.write.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LatestRoute = LatestRouteImport.update({
  id: '/latest',
  path: '/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsroomRoute = NewsroomRouteImport.update({
  id: '/newsroom',
  path: '/newsroom',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuthorsRoute = AdminAuthorsRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOversightRoute = AdminOversightRouteImport.update({
  id: '/oversight',
  path: '/oversight',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTagsRoute = AdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AdminRoute,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthJournalistRoute = AuthJournalistRouteImport.update({
  id: '/journalist',
  path: '/journalist',
  getParentRoute: () => AuthRoute,
} as any)
const AuthStaffRoute = AuthStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthRoute,
} as any)
const AuthorSlugRoute = AuthorSlugRouteImport.update({
  id: '/author/$slug',
  path: '/author/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsroomIndexRoute = NewsroomIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsroomRoute,
} as any)
const NewsroomProfileRoute = NewsroomProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => NewsroomRoute,
} as any)
const TagSlugRoute = TagSlugRouteImport.update({
  id: '/tag/$slug',
  path: '/tag/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsIdRoute = AdminPostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewIdRoute = AdminReviewIdRouteImport.update({
  id: '/review/$id',
  path: '/review/$id',
  getParentRoute: () => AdminRoute,
} as any)
const NewsroomWriteIdRoute = NewsroomWriteIdRouteImport.update({
  id: '/write/$id',
  path: '/write/$id',
  getParentRoute: () => NewsroomRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/join': typeof JoinRoute
  '/latest': typeof LatestRoute
  '/newsroom': typeof NewsroomRouteWithChildren
  '/search': typeof SearchRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/authors': typeof AdminAuthorsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/oversight': typeof AdminOversightRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/journalist': typeof AuthJournalistRoute
  '/auth/staff': typeof AuthStaffRoute
  '/author/$slug': typeof AuthorSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/newsroom/profile': typeof NewsroomProfileRoute
  '/tag/$slug': typeof TagSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/newsroom/': typeof NewsroomIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/review/$id': typeof AdminReviewIdRoute
  '/newsroom/write/$id': typeof NewsroomWriteIdRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/join': typeof JoinRoute
  '/latest': typeof LatestRoute
  '/search': typeof SearchRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/authors': typeof AdminAuthorsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/oversight': typeof AdminOversightRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/journalist': typeof AuthJournalistRoute
  '/auth/staff': typeof AuthStaffRoute
  '/author/$slug': typeof AuthorSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/newsroom/profile': typeof NewsroomProfileRoute
  '/tag/$slug': typeof TagSlugRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/newsroom': typeof NewsroomIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/review/$id': typeof AdminReviewIdRoute
  '/newsroom/write/$id': typeof NewsroomWriteIdRoute
  '/admin/posts': typeof AdminPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/join': typeof JoinRoute
  '/latest': typeof LatestRoute
  '/newsroom': typeof NewsroomRouteWithChildren
  '/search': typeof SearchRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/authors': typeof AdminAuthorsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/oversight': typeof AdminOversightRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/journalist': typeof AuthJournalistRoute
  '/auth/staff': typeof AuthStaffRoute
  '/author/$slug': typeof AuthorSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/newsroom/profile': typeof NewsroomProfileRoute
  '/tag/$slug': typeof TagSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/newsroom/': typeof NewsroomIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/review/$id': typeof AdminReviewIdRoute
  '/newsroom/write/$id': typeof NewsroomWriteIdRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/join'
    | '/latest'
    | '/newsroom'
    | '/search'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/authors'
    | '/admin/categories'
    | '/admin/comments'
    | '/admin/media'
    | '/admin/oversight'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/submissions'
    | '/admin/tags'
    | '/article/$slug'
    | '/auth/admin'
    | '/auth/journalist'
    | '/auth/staff'
    | '/author/$slug'
    | '/category/$slug'
    | '/newsroom/profile'
    | '/tag/$slug'
    | '/admin/'
    | '/auth/'
    | '/newsroom/'
    | '/admin/posts/$id'
    | '/admin/review/$id'
    | '/newsroom/write/$id'
    | '/admin/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/contact'
    | '/join'
    | '/latest'
    | '/search'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/authors'
    | '/admin/categories'
    | '/admin/comments'
    | '/admin/media'
    | '/admin/oversight'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/submissions'
    | '/admin/tags'
    | '/article/$slug'
    | '/auth/admin'
    | '/auth/journalist'
    | '/auth/staff'
    | '/author/$slug'
    | '/category/$slug'
    | '/newsroom/profile'
    | '/tag/$slug'
    | '/admin'
    | '/auth'
    | '/newsroom'
    | '/admin/posts/$id'
    | '/admin/review/$id'
    | '/newsroom/write/$id'
    | '/admin/posts'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/join'
    | '/latest'
    | '/newsroom'
    | '/search'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/authors'
    | '/admin/categories'
    | '/admin/comments'
    | '/admin/media'
    | '/admin/oversight'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/submissions'
    | '/admin/tags'
    | '/article/$slug'
    | '/auth/admin'
    | '/auth/journalist'
    | '/auth/staff'
    | '/author/$slug'
    | '/category/$slug'
    | '/newsroom/profile'
    | '/tag/$slug'
    | '/admin/'
    | '/auth/'
    | '/newsroom/'
    | '/admin/posts/$id'
    | '/admin/review/$id'
    | '/newsroom/write/$id'
    | '/admin/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ContactRoute: typeof ContactRoute
  JoinRoute: typeof JoinRoute
  LatestRoute: typeof LatestRoute
  NewsroomRoute: typeof NewsroomRouteWithChildren
  SearchRoute: typeof SearchRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  AuthorSlugRoute: typeof AuthorSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
  TagSlugRoute: typeof TagSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest': {
      id: '/latest'
      path: '/latest'
      fullPath: '/latest'
      preLoaderRoute: typeof LatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsroom': {
      id: '/newsroom'
      path: '/newsroom'
      fullPath: '/newsroom'
      preLoaderRoute: typeof NewsroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/authors': {
      id: '/admin/authors'
      path: '/authors'
      fullPath: '/admin/authors'
      preLoaderRoute: typeof AdminAuthorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/oversight': {
      id: '/admin/oversight'
      path: '/oversight'
      fullPath: '/admin/oversight'
      preLoaderRoute: typeof AdminOversightRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tags': {
      id: '/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminTagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/admin': {
      id: '/auth/admin'
      path: '/admin'
      fullPath: '/auth/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/journalist': {
      id: '/auth/journalist'
      path: '/journalist'
      fullPath: '/auth/journalist'
      preLoaderRoute: typeof AuthJournalistRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/staff': {
      id: '/auth/staff'
      path: '/staff'
      fullPath: '/auth/staff'
      preLoaderRoute: typeof AuthStaffRouteImport
      parentRoute: typeof AuthRoute
    }
    '/author/$slug': {
      id: '/author/$slug'
      path: '/author/$slug'
      fullPath: '/author/$slug'
      preLoaderRoute: typeof AuthorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsroom/': {
      id: '/newsroom/'
      path: '/'
      fullPath: '/newsroom/'
      preLoaderRoute: typeof NewsroomIndexRouteImport
      parentRoute: typeof NewsroomRoute
    }
    '/newsroom/profile': {
      id: '/newsroom/profile'
      path: '/profile'
      fullPath: '/newsroom/profile'
      preLoaderRoute: typeof NewsroomProfileRouteImport
      parentRoute: typeof NewsroomRoute
    }
    '/tag/$slug': {
      id: '/tag/$slug'
      path: '/tag/$slug'
      fullPath: '/tag/$slug'
      preLoaderRoute: typeof TagSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/posts'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/$id': {
      id: '/admin/posts/$id'
      path: '/posts/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AdminPostsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/review/$id': {
      id: '/admin/review/$id'
      path: '/review/$id'
      fullPath: '/admin/review/$id'
      preLoaderRoute: typeof AdminReviewIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/newsroom/write/$id': {
      id: '/newsroom/write/$id'
      path: '/write/$id'
      fullPath: '/newsroom/write/$id'
      preLoaderRoute: typeof NewsroomWriteIdRouteImport
      parentRoute: typeof NewsroomRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminAuthorsRoute: typeof AdminAuthorsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminOversightRoute: typeof AdminOversightRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminTagsRoute: typeof AdminTagsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPostsIdRoute: typeof AdminPostsIdRoute
  AdminReviewIdRoute: typeof AdminReviewIdRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminAuthorsRoute: AdminAuthorsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCommentsRoute: AdminCommentsRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminOversightRoute: AdminOversightRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminTagsRoute: AdminTagsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPostsIdRoute: AdminPostsIdRoute,
  AdminReviewIdRoute: AdminReviewIdRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRoute
  AuthJournalistRoute: typeof AuthJournalistRoute
  AuthStaffRoute: typeof AuthStaffRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRoute,
  AuthJournalistRoute: AuthJournalistRoute,
  AuthStaffRoute: AuthStaffRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface NewsroomRouteChildren {
  NewsroomProfileRoute: typeof NewsroomProfileRoute
  NewsroomIndexRoute: typeof NewsroomIndexRoute
  NewsroomWriteIdRoute: typeof NewsroomWriteIdRoute
}

const NewsroomRouteChildren: NewsroomRouteChildren = {
  NewsroomProfileRoute: NewsroomProfileRoute,
  NewsroomIndexRoute: NewsroomIndexRoute,
  NewsroomWriteIdRoute: NewsroomWriteIdRoute,
}

const NewsroomRouteWithChildren = NewsroomRoute._addFileChildren(
  NewsroomRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ContactRoute: ContactRoute,
  JoinRoute: JoinRoute,
  LatestRoute: LatestRoute,
  NewsroomRoute: NewsroomRouteWithChildren,
  SearchRoute: SearchRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  AuthorSlugRoute: AuthorSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
  TagSlugRoute: TagSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
